version: '3.2'

services:

    tvmazescraper-api:
        container_name: restapi
        build:
            context: .
            dockerfile: src/TvMazeScraper.Api/dockerfile          
        restart: always
        depends_on:
            - mongodb
        links:
            - mongodb
        ports:
            - 5000:5000   
        environment:    
            ASPNETCORE_URLS: http://*:5000

            
    tvmazescraper-app:
        container_name: application
        build:
            context: .
            dockerfile: src/TvMazeScraper/dockerfile
        restart: always
        depends_on:
            - mongodb
        links:
            - mongodb                
            
    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - 27017:27017
        restart: always  
    
                          